name: base
channels:
  - conda-forge
dependencies:
  - babel=2.11.0
  - bcrypt=3.2.0
  - beautifulsoup4=4.12.3
  - binaryornot=0.4.4
  - black=24.8.0
  - blas=1.0
  - bleach=4.1.0
  - blinker=1.6.2
  - blosc=1.21.3
  - bokeh=3.6.0
  - boltons=23.0.0
  - boost-cpp=1.82.0
  - botocore=1.34.69
  - bottleneck=1.3.7
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - brunsli=0.1
  - bzip2=1.0.8
  - c-ares=1.19.1
  - c-blosc2=2.12.0
  - ca-certificates=2025.1.31
  - cachetools=5.3.3
  - cctools=949.0.1
  - cctools_osx-arm64=949.0.1
  - certifi=2025.1.31
  - cffi=1.17.1
  - cfitsio=3.470
  - chardet=4.0.0
  - charls=2.2.0
  - charset-normalizer=3.3.2
  - click=8.1.7
  - cloudpickle=3.0.0
  - colorama=0.4.6
  - colorcet=3.1.0
  - curl=8.9.1
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - cytoolz=0.12.2
  - dask=2024.8.2
  - dask-core=2024.8.2
  - dask-expr=1.1.13
  - datashader=0.16.3
  - fonttools=4.51.0
  - freetype=2.12.1
  - frozendict=2.4.2
  - frozenlist=1.4.0
  - fsspec=2024.6.1
  - gensim=4.3.3
  - gettext=0.21.0
  - gflags=2.2.2
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.43
  - glib=2.78.4
  - glib-tools=2.78.4
  - glog=0.5.0
  - greenlet=3.0.1
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - h11=0.14.0
  - h5py=3.11.0
  - hdf5=1.12.1
  - heapdict=1.0.1
  - holoviews=1.19.1
  - httpcore=1.0.2
  - httpx=0.27.0
  - hvplot=0.11.0
  - hyperlink=21.0.0
  - icu=73.1
  - idna=3.7
  - imagecodecs=2023.1.23
  - imageio=2.33.1
  - imagesize=1.4.1
  - imbalanced-learn=0.12.3
  - importlib-metadata=7.0.1
  - incremental=22.10.0
  - inflection=0.5.1
  - iniconfig=1.1.1
  - intake=2.0.7
  - intervaltree=3.1.0
  - ipykernel=6.28.0
  - ipython=8.27.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.1.5
  - isort=5.13.2
  - itemadapter=0.3.0
  - itemloaders=1.1.0
  - itsdangerous=2.2.0
  - jaraco.classes=3.2.1
  - jedi=0.19.1
  - jellyfish=1.0.1
  - jinja2=3.1.4
  - jmespath=1.0.1
  - joblib=1.4.2
  - jpeg=9e
  - jq=1.6
  - json5=0.9.6
  - jsonpatch=1.33
  - jsonpointer=2.1
  - jsonschema=4.23.0
  - jsonschema-specifications=2023.7.1
  - jupyter=1.0.0
  - jupyter-lsp=2.2.0
  - jupyter_client=8.6.0
  - jupyter_console=6.6.3
  - jupyter_core=5.7.2
  - jupyter_events=0.10.0
  - jupyter_server=2.14.1
  - jupyter_server_terminals=0.4.4
  - jupyterlab=4.2.5
  - jupyterlab-variableinspector=3.1.0
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.27.3
  - jupyterlab_widgets=3.0.13
  - jxrlib=1.1
  - keyring=24.3.1
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lazy-object-proxy=1.10.0
  - lazy_loader=0.4
  - lcms2=2.12
  - ld64=530
  - ld64_osx-arm64=530
  - ldid=2.1.5
  - lerc=3.0
  - libabseil=20240116.2
  - libaec=1.0.4
  - libarchive=3.7.4
  - libavif=0.11.1
  - libboost=1.82.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.9.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20230828
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.6.3
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libgrpc=1.62.2
  - libiconv=1.16
  - liblief=0.12.3
  - libllvm14=14.0.6
  - libmamba=1.5.8
  - libmambapy=1.5.8
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libpq=12.17
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libsolv=0.7.24
  - libspatialindex=1.9.3
  - libsqlite=3.46.0
  - libssh2=1.11.0
  - libthrift=0.15.0
  - libtiff=4.5.1
  - libwebp-base=1.3.2
  - libxml2=2.13.1
  - libxslt=1.1.41
  - libzlib=1.2.13
  - libzopfli=1.0.3
  - linkify-it-py=2.0.0
  - llvm-openmp=14.0.6
  - llvmlite=0.43.0
  - locket=1.0.0
  - lxml=5.2.1
  - lz4=4.3.2
  - lz4-c=1.9.4
  - lzo=2.10
  - mako=1.2.3
  - markdown=3.4.1
  - markdown-it-py=2.2.0
  - markupsafe=2.1.3
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.6
  - mccabe=0.7.0
  - mdit-py-plugins=0.3.0
  - mdurl=0.1.0
  - menuinst=2.1.2
  - mistune=2.0.4
  - more-itertools=10.3.0
  - mpmath=1.3.0
  - msgpack-python=1.0.3
  - multidict=6.0.4
  - multipledispatch=0.6.0
  - mypy=1.11.2
  - mypy_extensions=1.0.0
  - mysql=5.7.24
  - navigator-updater=0.5.1
  - nb_conda_kernels=2.5.2
  - nbclient=0.8.0
  - nbconvert=7.16.4
  - nbformat=5.10.4
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - networkx=3.3
  - nltk=3.9.1
  - notebook=7.2.2
  - notebook-shim=0.2.3
  - numba=0.60.0
  - numexpr=2.8.7
  - numpy=1.26.4
  - numpy-base=1.26.4
  - numpydoc=1.7.0
  - oniguruma=6.9.7.1
  - openjpeg=2.5.2
  - openpyxl=3.1.5
  - openssl=3.4.1
  - orc=2.0.1
  - overrides=7.4.0
  - packaging=24.1
  - pandas=2.2.2
  - pandocfilters=1.5.0
  - panel=1.5.2
  - param=2.1.1
  - parsel=1.8.1
  - parso=0.8.3
  - partd=1.4.1
  - patch=2.7.6
  - pathspec=0.10.3
  - patsy=0.5.6
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pkce=1.0.3
  - pkginfo=1.10.0
  - platformdirs=3.10.0
  - plotly=5.24.1
  - pluggy=1.0.0
  - ply=3.11
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.43
  - prompt_toolkit=3.0.43
  - protego=0.1.16
  - protobuf=4.25.3
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - py-cpuinfo=9.0.0
  - py-lief=0.12.3
  - pyarrow=16.1.0
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pybind11-abi=5
  - pycodestyle=2.11.1
  - pycosat=0.6.6
  - pycparser=2.21
  - pyct=0.5.0
  - pycurl=7.45.3
  - pydantic=2.8.2
  - pydantic-core=2.20.1
  - pydantic-settings=2.6.1
  - pydeck=0.8.0
  - pydispatcher=2.0.5
  - pydocstyle=6.3.0
  - pyerfa=2.0.1.4
  - pyflakes=3.2.0
  - pygments=2.15.1
  - pyjwt=2.8.0
  - pylint=2.16.2
  - pylint-venv=3.0.3
  - pyls-spyder=0.4.0
  - pyobjc-core=10.1
  - pyobjc-framework-cocoa=10.1
  - pyobjc-framework-coreservices=10.1
  - pyobjc-framework-fsevents=10.1
  - pyodbc=5.1.0
  - pyopenssl=24.2.1
  - pyparsing=3.1.2
  - pyqt=5.15.10
  - pyqt5-sip=12.13.0
  - pyqtwebengine=5.15.10
  - pysocks=1.7.1
  - pytables=3.10.1
  - pytest=7.4.4
  - python=3.12.2
  - python-dateutil=2.9.0post0
  - python-dotenv=0.21.0
  - python-fastjsonschema=2.16.2
  - python-json-logger=2.0.7
  - python-libarchive-c=5.1
  - python-lmdb=1.4.1
  - python-lsp-black=2.0.0
  - python-lsp-jsonrpc=1.1.2
  - python-lsp-server=1.10.0
  - python-slugify=5.0.2
  - python-tzdata=2023.3
  - python.app=3
  - python_abi=3.12
  - pytoolconfig=1.2.6
  - pytz=2024.1
  - pyviz_comms=3.0.2
  - pywavelets=1.7.0
  - pyyaml=6.0.1
  - pyzmq=25.1.2
  - qdarkstyle=3.2.3
  - qstylizer=0.2.2
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtawesome=1.3.1
  - qtconsole=5.5.1
  - qtpy=2.4.1
  - queuelib=1.6.2
  - re2=2022.04.01
  - readchar=4.0.5
  - readline=8.2
  - referencing=0.30.2
  - regex=2024.9.11
  - reproc=14.2.4
  - reproc-cpp=14.2.4
  - requests=2.32.3
  - requests-file=1.5.1
  - requests-toolbelt=1.0.0
  - rfc3339-validator=0.1.4
  - rfc3986-validator=0.1.1
  - rich=13.7.1
  - rope=1.12.0
  - rpds-py=0.10.6
  - rtree=1.0.1
  - ruamel.yaml=0.18.6
  - ruamel.yaml.clib=0.2.8
  - ruamel_yaml=0.17.21
  - s3fs=2024.6.1
  - scikit-image=0.24.0
  - scikit-learn=1.5.1
  - scipy=1.13.1
  - scrapy=2.11.1
  - seaborn=0.13.2
  - semver=3.0.2
  - send2trash=1.8.2
  - sentry-sdk=2.18.0
  - service_identity=18.1.0
  - setuptools=75.1.0
  - shellingham=1.5.0
  - sip=6.7.12
  - six=1.16.0
  - smart_open=5.2.1
  - smmap=4.0.0
  - snappy=1.2.1
  - sniffio=1.3.0
  - snowballstemmer=2.2.0
  - sortedcontainers=2.4.0
  - soupsieve=2.5
  - sphinx=7.3.7
  - sphinxcontrib-applehelp=1.0.2
  - sphinxcontrib-devhelp=1.0.2
  - sphinxcontrib-htmlhelp=2.0.0
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.3
  - sphinxcontrib-serializinghtml=1.1.10
  - spyder=5.5.1
  - spyder-kernels=2.5.0
  - sqlalchemy=2.0.34
  - sqlite=3.45.3
  - stack_data=0.2.0
  - statsmodels=0.14.2
  - streamlit=1.37.1
  - sympy=1.13.2
  - tabulate=0.9.0
  - tapi=1100.0.11
  - tbb=2021.8.0
  - tblib=1.7.0
  - tenacity=8.2.3
  - terminado=0.17.1
  - text-unidecode=1.3
  - textdistance=4.2.1
  - threadpoolctl=3.5.0
  - three-merge=0.1.1
  - tifffile=2023.4.12
  - tinycss2=1.2.1
  - tk=8.6.14
  - tldextract=5.1.2
  - toml=0.10.2
  - tomli=2.0.1
  - tomlkit=0.11.1
  - toolz=0.12.0
#  - tornado=6.4.1
  - tqdm=4.66.5
  - traitlets=5.14.3
  - truststore=0.8.0
  - twisted=23.10.0
  - typer=0.9.0
  - typing-extensions=4.11.0
  - typing_extensions=4.11.0
  - tzdata=2024b
  - uc-micro-py=1.0.1
  - ujson=5.10.0
  - unicodedata2=15.1.0
  - unidecode=1.3.8
  - unixodbc=2.3.11
  - urllib3=2.2.3
  - utf8proc=2.6.1
  - voila=0.5.8
  - w3lib=2.1.2
  - watchdog=4.0.1
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=1.8.0
  - websockets=15.0.1
  - werkzeug=3.0.3
  - whatthepatch=1.0.2
  - wheel=0.44.0
  - widgetsnbextension=4.0.13
  - wrapt=1.14.1
  - wurlitzer=3.0.2
  - xlwings=0.32.1
  - xyzservices=2022.9.0
  - xz=5.4.6
  - yaml=0.2.5
  - yaml-cpp=0.8.0
  - yapf=0.40.2
  - yarl=1.11.0
  - zeromq=4.3.5
  - zfp=1.0.0
  - zict=3.0.0
  - zipp=3.17.0
  - zlib=1.2.13
  - zlib-ng=2.0.7
  - zope=1.0
  - zope.interface=5.4.0
  - zstandard=0.23.0
  - zstd=1.5.6
  - pip:
      - affine==2.4.0
      - anywidget==0.9.15
      - bqplot==0.12.44
      - branca==0.8.1
      - click-plugins==1.1.1
      - cligj==0.7.2
      - colour==0.1.5
      - contextily==1.6.2
      - duckdb==1.2.1
      - earthpy==0.9.4
      - folium==0.19.5
      - fqdn==1.5.1
      - gdown==5.2.0
      - geographiclib==2.0
      - geojson==3.2.0
      - geopandas==1.0.1
      - geopy==2.4.1
      - gurobipy==11.0.0
      - ipyevents==2.0.2
      - ipyfilechooser==0.6.0
      - ipyleaflet==0.19.2
      - ipytree==0.2.2
      - ipyvue==1.11.2
      - ipyvuetify==1.11.1
      - isoduration==20.11.0
      - jupyter-leaflet==0.19.2
      - leafmap==0.42.13
      - looseversion==1.3.0
      - mapclassify==2.8.1
      - matplotlib-venn==1.1.2
      - mercantile==1.2.1
      - psygnal==0.12.0
      - pyogrio==0.10.0
      - pyproj==3.7.1
      - pysheds==0.4
      - pyshp==2.3.1
      - pystac==1.12.2
      - pystac-client==0.8.6
      - python-box==7.3.2
      - rasterio==1.4.3
      - rioxarray==0.18.2
      - scooby==0.10.0
      - shapely==2.0.7
      - traittypes==0.2.1
      - uri-template==1.3.0
      - webcolors==24.11.1
      - whitebox==2.3.6
      - whiteboxgui==2.3.0
      - xarray==2025.1.2
